# Metadata for this specific system configuration preset

config_version = 1

# Name of the system; used internally to reference it and for paths, etc.
name = "hamma"

# Full "pretty" name of the system, e.g. for UI text
name_full = "HAMMA Sensor System"
# The author, authors or sponsoring organization of the system
author = "C.A.M. Gerlach and the UAH HAMMA group"
# Freeform description of the system's intended function and purpose
description = "System configuration for the Huntsville AL Marx Meter Array"
# Official website for this specific system
homepage = "https://hamma.dev/"
# Repository containing the system's source code
repo = "https://github.com/hamma-dev/mjolnir-hamma"
# SPDX license identifier for the this configuration package (TBD)
license = ""

# Version of the config package; should follow SemVer and PEP 396
version = "0.1.0"
# Minimun Brokkr version this version of the config package needs to work
brokkr_version_min = "0.3.0"
# Ibid, for Sindri
sindri_version_min = "0.3.0"
