config_version = 1
name = "hamma2"
type = "device"

[metadata]
name_full = "HAMMA2 Sensor"
author = "C.A.M. Gerlach and the UAH HAMMA group"
description = "Device preset for the Huntsville AL Marx Meter Array version 2 sensor"
homepage = "https://hamma.dev/"
repo = "https://github.com/hamma-dev/mjolnir-hamma"
preset_version = "0.1.0"
brokkr_version_min = "0.3.0"

[type_presets]
gigabytes = { conversion = "custom", binary_type = "Q", unit = "GB", uncertainty = false, base = 10, power = -9, digits = 9 }

[data_types]
marker_val = { input_type = "8s", conversion = false }
sequence_count = { binary_type = "I", unit = "", uncertainty = false }
timestamp = { binary_type = "q", conversion = "time_posix_ms", unit = "s", uncertainty = 0.001 }
crc_errors = { full_name = "CRC Errors", binary_type = "I", unit = "", uncertainty = false }
valid_packets = { binary_type = "I", unit = "", uncertainty = false }
bytes_read = { full_name = "Data Read", type_presets = "gigabytes" }
bytes_written = { full_name = "Data Written", type_presets = "gigabytes" }
bytes_remaining = { full_name = "Disk Remaining", type_presets = "gigabytes" }
packets_sent = { binary_type = "I", unit = "", uncertainty = false }
packets_dropped = { binary_type = "I", unit = "", uncertainty = false }

[inputs.ping]
_module_path = "brokkr.inputs.ping"
_class_name = "PingInput"
name = "Sensor Ping"
host = "10.10.10.1"
timeout_s = 1

[inputs.hs]
_module_path = "brokkr.inputs.udp"
_class_name = "UDPInput"
name = "Sensor Health & Status Packet"
host = "10.10.10.2"
port = 8084
timeout_s = 2
data_types = [
    "marker_val",
    "sequence_count",
    "timestamp",
    "crc_errors",
    "valid_packets",
    "bytes_read",
    "bytes_written",
    "bytes_remaining",
    "packets_sent",
    "packets_dropped",
]
