# Shared static system configuration

config_version = 1

[general]
monitoring_pipeline_default = "telemetry"
output_filename_client = "{output_type}_{system_prefix}_{unit_number:0>3}_{utc_date!s}.{extension}"
output_path_client = "~/brokkr/{system_name}"
worker_shutdown_wait_s = 10

[autossh]
server_hostname = "proxy.nsstc.uah.edu"
server_username = "mjolnir"
tunnel_port_offset = 10000

[steps.telemetry_csv_output]
_preset = "builtins.outputs.csv_file"
name = "Telemetry CSV Output"
output_path = "telemetry"
filename_kwargs = { output_type = "telemetry" }

[pipelines.telemetry]
_builder = "monitor"
name = "Telemetry"
monitor_interval_s = 60
monitor_input_steps = [
    "builtins.inputs.current_time",
    "builtins.inputs.run_time",
    "sunsaver_mppt_15l.inputs.ram",
    "hamma2.inputs.ping",
    "hamma2.inputs.hs",
]
monitor_output_steps = [ "telemetry_csv_output" ]
