# Shared static system configuration, not updated during runtime

config_version = 1

[general]
ip_local = "10.10.10.2"
ip_sensor = "10.10.10.1"
na_marker = "NA"
output_filename_client = "{output_type}_{system_prefix}_{unit_number:0>3}_{utc_date!s}.{extension}"
output_path_client = "~/brokkr/{system_name}"

[link]
server_hostname = "proxy.nsstc.uah.edu"
server_port = 22
server_username = "mjolnir"
tunnel_port_offset = 10000

[monitor]
output_path_client = "telemetry"
filename_kwargs = { output_type = "telemetry" }
hs_port = 8084
hs_timeout_s = 2
interval_s = 60
ping_timeout_s = 1
sunsaver_pid_list = [24597,]
sunsaver_port = ""
sunsaver_start_offset = 8
sunsaver_unit = 1
