# Shared config mode preset configuration

config_version = 1

[realtime.main.general]
output_path_client = "~/brokkr/realtime"

[realtime.main.pipelines.telemetry]
monitor_interval_s = 1

[test.main.general]
output_path_client = "~/brokkr/test"

[test.main.pipelines.telemetry]
monitor_interval_s = 5
